apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: {{DEVICE_NAME}}-{{DEVICE_ID}}-configmap-app
  name: {{DEVICE_NAME}}-{{DEVICE_ID}}-route
  namespace: device-apps
spec:
  host: "{{DEVICE_NAME}}-{{DEVICE_ID}}.apps.{{CLUSTER_FQDN}}"
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  to:
    kind: Service
    name: {{DEVICE_NAME}}-{{DEVICE_ID}}-service
    weight: 100
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
